### ISSUE TITLE
FATAL: Improperly formatted configuration file mimosa-config.coffee: Error: Cannot find module 'emblem'

### ISSUE THREAD

**Issue by shobhz** [breatheforks/mimosa-peepcode#13]
I simply created a project using 

```
$ mimosa skel:new ember-peepcode my-app
$ npm install
$ bower install
```

And built it 

```
$ mimosa watch -s
```

I get the error **FATAL: Improperly formatted configuration file mimosa-config.coffee: Error: Cannot find module 'emblem'**

I even tried cloning the mimosa-peepcode. Still the same error.

**Comment by breathe** [comment]
I wouldn't recommend any of the patterns/tools in this repo for building new apps -- I've moved on to react and webpack -- you should check those out if you are looking for something to learn ...  I'll add a note that this is a dead project to the readme

**Comment by shobhz** [comment]
Thanks.. Will do!!

On Sun, Sep 6, 2015 at 8:09 PM breathe notifications@github.com wrote:

> I wouldn't recommend any of the patterns/tools in this repo for building
> new apps -- I've moved on to react and webpack -- you should check those
> out if you are looking for something to learn ... I'll add a note that this
> is a dead project to the readme
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/breathe/mimosa-peepcode/issues/13#issuecomment-138090264
> .
> 
> ## 
> 
> Regards,
> Shobhan Vijay,

_(+91) 99416 72254Facebook https://www.facebook.com/shobhnvijay | Twitter
https://twitter.com/Shob_z | Linkedin
https://in.linkedin.com/pub/shobhan-vijay-madeshwaran/15/7a3/892 | Skype
ID: shobz92_
