### ISSUE TITLE
Latest Mimosa requires Handlebars 1.0

### ISSUE THREAD

**Issue by dbashford** [breatheforks/mimosa-peepcode#4]
Application and tests break when on older version of handlebars.

Could you verify what version of Mimosa you are using to make this work?

**Comment by breathe** [comment]
I was using 0.14.5 -- however I couldn't the project to work with emblem 0.2.9 and handlebars 1.0.11 (named 1.0.0-rc4 in browser).

I thought I had handlebars 1.0.12 and emblem 0.3.0 in the projects package.json ...  Did I mess it up?  I don't have a computer with me at the moment ...

**Comment by breathe** [comment]
Ah I think I see what may be going on.   I removed the ./test directory but accidentally didn't get that change into the commit I pushed ...  Let me double check if any other files missed their way into the commit (possibly the manually downloaded assets/javascripts/handlebars.js)

My concept with the testem changes was to move the testrunner into the same relative URL context as the normal app ..  Does everything work if you remove the ./test directory?

**Comment by breathe** [comment]
So here are all the changes I need to make -
- remove ./test directory
- remove ./assets/javascripts/vendor/handlebars.js
- add handlebars-1.0.0 to bower.json (it's now available there)
- change script tag of handlebars in index.jade to ./javascripts/vendor/bower-assets/handlebars/handlebars.js
- set minMimosaVersion to 0.14.5 to ensure correct emblem pre compiler version is used

Does that look right to you?  I only brought my phone with me on this trip so I might not being to fix this as quickly as I would like ...

I'm not sure how I got the version on github so messed up -- i think i made these edits but failed to get them all int the commit somehow ... dangers of multitasking ...

**Comment by dbashford** [comment]
I'll give those a go in a fork and if it all works all you'll have to do is merge the PR =)

**Comment by breathe** [comment]
That would be rad!  I should note that I edited that comment a bunch of times not sure which you might have gotten ...

**Comment by dbashford** [comment]
Looking at the latest. =)

Small problem:

```
handlebars: Unable to find suitable version for handlebars: handlebars@1.0.0-rc.4, handlebars@1.0.0
```

Guessing Ember clashes with 1.0.0.  Might that be why you bypassed bower for and added handlebars to `/assets/javascripts/vendor/handlebars.js`?

**Comment by breathe** [comment]
Ho humm -- is that with handlebars-1.0.0 in bower.json?  I thought that 1.0.0 was on bower now ...?

**Comment by dbashford** [comment]
Ya, what's happening here is Bower is looking at the `bower.json`, it seems `handlebars@1.0.0` then it looks at `ember` and all of ember's dependencies, and it sees `handlebars@1.0.0-rc.4` and it throws its hands up in the air, doesn't know what to do, and errors out.  Actually errors out.  Mimosa slides in there and provides a useful message, but the bower install essentially crashes and there's no much Mimosa can do about it.  It is something that has to be resolved via the `bower.json` alone.

**Comment by breathe** [comment]
Maybe it's better to just use the handlebars 1.0.0 manually downloaded along with ember.js and jquery from ember-starter-kit for now -- can wait for the next ember release to (hopefully) use the bower versions ...  Those changes in index.jade and testrunner.html along with minMimosaVersion should fix everything ...?

**Comment by dbashford** [comment]
PR sent.

Didn't remove `.test` directory as the `testrunner.html` is in there.  Guessing I could have removed the other test assets?

Otherwise everything is dealing with `vendor/handlebars`

**Comment by dbashford** [comment]
All good now =)
